name: build and push docker image

on:
  push:
    branches:
      - master

jobs:
  build-base-image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup qemu
        uses: docker/setup-qemu-action@v1
      - name: setup docker buildx
        uses: docker/setup-buildx-action@v1
      - name: login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: build base
        uses: docker/build-push-action@v2
        with:
          tags: ${{ secrets.DOCKERHUB_USER }}/tilt-example-go:base-${{ github.sha }}
          context: "0-base"
          file: "0-base/deployments/Dockerfile"
          push: true
  build-measured-image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup qemu
        uses: docker/setup-qemu-action@v1
      - name: setup docker buildx
        uses: docker/setup-buildx-action@v1
      - name: login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: build measured
        uses: docker/build-push-action@v2
        with:
          tags: ${{ secrets.DOCKERHUB_USER }}/tilt-example-go:measured-${{ github.sha }}
          context: "1-measured"
          file: "1-measured/deployments/Dockerfile"
          push: true
  build-optimized-image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup qemu
        uses: docker/setup-qemu-action@v1
      - name: setup docker buildx
        uses: docker/setup-buildx-action@v1
      - name: setup go
        uses: actions/setup-go@v2
      - name: login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: build app
        working-directory: ./2-optimized
        run: go build -o build/tilt-example-go ./
      - name: build optimized
        uses: docker/build-push-action@v2
        with:
          tags: ${{ secrets.DOCKERHUB_USER }}/tilt-example-go:optimized-${{ github.sha }}
          context: "2-optimized"
          file: "2-optimized/deployments/Dockerfile"
          push: true
  build-recommended-image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup qemu
        uses: docker/setup-qemu-action@v1
      - name: setup docker buildx
        uses: docker/setup-buildx-action@v1
      - name: setup go
        uses: actions/setup-go@v2
      - name: login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: build app
        working-directory: ./3-recommended
        run: go build -o build/tilt-example-go ./
      - name: build recommended
        uses: docker/build-push-action@v2
        with:
          tags: ${{ secrets.DOCKERHUB_USER }}/tilt-example-go:recommended-${{ github.sha }}
          context: "3-recommended"
          file: "3-recommended/deployments/Dockerfile"
          push: true
